# Generated by Django 5.2.4 on 2025-07-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_annonce_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='statut',
            field=models.TextField(null=True),
        ),
    ]
