# Generated by Django 5.2.4 on 2025-07-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='statut',
            field=models.TextField(blank=True, choices=[('validee', 'Validée'), ('rejetee', 'Rejetée'), ('attente', 'En attente')], null=True),
        ),
    ]
