# Generated by Django 5.2.4 on 2025-08-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'client'), ('ADMIN', 'admin')], default='CLIENT', max_length=6),
        ),
    ]
